name: Keep MedXpert Alive

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6 AM UTC
  workflow_dispatch:  # Allows you to run the workflow manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run keep_alive.py  
        run: python keep_alive.py
